type Query
type Mutation

scalar File
scalar DateTime

# Enums

enum LoyaltyCardType {
  BAHNCARD
  VORTEILSCARD
  HALBTAXABO
  VOORDEELURENABO
  SHCARD
  GENERALABONNEMENT
  NL_40
  AT_KLIMATICKET
}

enum AgeGroup {
  BABY
  CHILD
  YOUTH
  ADULT
  SENIOR
}

# Shared types & inputs

type LoyaltyCard {
  type: LoyaltyCardType!
  discount: Int
  class: Int
}

input LoyaltyCardInput {
  type: LoyaltyCardType!
  discount: Int
  class: Int
}

input ProductFilter {
  nationalExpress: Boolean
  national: Boolean
  regionalExpress: Boolean
  regional: Boolean
  suburban: Boolean
  bus: Boolean
  ferry: Boolean
  subway: Boolean
  tram: Boolean
  taxi: Boolean
}

input JourneySearchOptions {
  firstClass: Boolean
  loyaltyCard: LoyaltyCardInput
  ageGroup: AgeGroup
  deutschlandTicketDiscount: Boolean
  products: ProductFilter
  transfers: Int
  transferTime: Int
  bike: Boolean
  results: Int
}

# User

type User {
  id: ID!
  givenName: String!
  familyName: String
  email: String!
  profilePicture: String
  emailNotificationsEnabled: Boolean!
  loyaltyCards: [LoyaltyCard!]
  ageGroup: AgeGroup
  deutschlandTicketDiscount: Boolean
  notifications(limit: Int, read: Boolean): [Notification]
  journeyMonitors(limit: Int): [JourneyMonitor]
}

type PresignedUrl {
  id: ID!
  url: String
}

## Queries

extend type Query {
  user(id: ID!): User
}

extend type Query {
  userProfilePicturePresignedUrl(id: ID!): PresignedUrl
}

## Mutations

extend type Mutation {
  updateUserProfilePicture(id: ID!, image: File!): User
}

extend type Mutation {
  createUser(id: ID!, givenName: String!, familyName: String, email: String!): User
}

extend type Mutation {
  updateUserSettings(id: ID!, emailNotificationsEnabled: Boolean!): User
}

extend type Mutation {
  updateTravelPreferences(
    userId: ID!
    loyaltyCards: [LoyaltyCardInput!]
    ageGroup: AgeGroup
    deutschlandTicketDiscount: Boolean
  ): User
}

extend type Mutation {
  deleteUser(id: ID!): User
}

# Notification

interface Notification {
  id: ID!
  type: ID!
  userId: ID!
  timestamp: DateTime!
  read: Boolean!
  sent: Boolean!
}

type PriceAlertNotification implements Notification {
  id: ID!
  type: ID!
  userId: ID!
  timestamp: DateTime!
  read: Boolean!
  sent: Boolean!
  journeyMonitor: JourneyMonitor!
}

type JourneyExpiryNotification implements Notification {
  id: ID!
  type: ID!
  userId: ID!
  timestamp: DateTime!
  read: Boolean!
  sent: Boolean!
  from: String!
  to: String!
}

type JourneyStaleNotification implements Notification {
  id: ID!
  type: ID!
  userId: ID!
  timestamp: DateTime!
  read: Boolean!
  sent: Boolean!
  journeyId: ID!
  from: String!
  to: String!
}

## Mutations

extend type Mutation {
  markNotificationAsRead(userId: ID!, notificationId: ID!): Notification
}

extend type Mutation {
  sendEmailNotification(userId: ID!, notificationId: ID!): Notification
}

# Journeys

type JourneysResult {
  journeys: [Journey]
  earlierRef: String
  laterRef: String
}

type Journey {
  refreshToken: String!
  fromId: String
  toId: String
  departure: DateTime
  arrival: DateTime
  means: [String]
  price: Float
}

type JourneyMonitor {
  id: ID!
  userId: ID!
  limitPrice: Float!
  expires: DateTime!
  journey: Journey
  from: String
  to: String
  firstClass: Boolean
  bike: Boolean
  deutschlandTicketDiscount: Boolean
  ageGroup: AgeGroup
  loyaltyCard: LoyaltyCard
}

## Queries

extend type Query {
  journeys(
    from: String!
    to: String!
    departure: DateTime!
    earlierThan: String
    laterThan: String
    options: JourneySearchOptions
  ): JourneysResult
}

## Mutations

extend type Mutation {
  monitorJourney(
    userId: ID!
    refreshToken: String!
    limitPrice: Float!
    expires: DateTime!
    fromId: String!
    toId: String!
    departure: DateTime!
    options: JourneySearchOptions
  ): JourneyMonitor
}

extend type Mutation {
  updateJourneyMonitors: Int
}

extend type Mutation {
  updateJourneyMonitor(userId: ID!, journeyId: ID!): JourneyMonitor
}

extend type Mutation {
  deleteJourneyMonitor(userId: ID!, journeyId: ID!): JourneyMonitor
}

# Locations

type Location {
  type: String!
  id: String!
  name: String!
}

extend type Query {
  locations(query: String!): [Location]
}
