min_version = "2024.9.5"
experimental_monorepo_root = true

[monorepo]
config_roots = ["frontend", "backend", "infrastructure"]

[tools]
node = "24"

[env]
_.file = '.env'
PROJECT_NAME = "train-price-monitor"
NODE_ENV = "development"
AWS_REGION = "eu-central-1"

[tasks.install]
description = "Install dependencies for all modules"
depends = ["//...:install"]

[tasks.dev]
alias = "s"
description = "Start frontend dev server"
depends = ["//frontend:dev"]

[tasks.build]
description = "Build all modules"
depends = ["//...:build"]

[tasks.lint]
alias = "l"
description = "Run ESLint on all modules"
depends = ["//...:lint"]

[tasks.test]
description = "Run tests"
depends = ["//...:test"]

[tasks.typecheck]
description = "Typecheck all modules"
depends = ["//...:typecheck"]

[tasks.deploy]
description = "Deploy all CDK stacks to AWS"
depends = ["//infrastructure:deploy"]
