repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  - repo: https://github.com/34j/mirrors-prettier
    rev: 'v3.8.3'
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v10.4.0'
    hooks:
      - id: eslint
        args: ['--max-warnings=0', '--config', 'eslint.config.cjs']
        additional_dependencies:
          - 'eslint@10.4.0'
          - '@typescript-eslint/eslint-plugin@8.58.2'
          - '@typescript-eslint/parser@8.58.2'
          - 'typescript@5.9.3'
          - 'globals@15.0.0'
          - 'eslint-plugin-react@7.37.5'
          - 'eslint-plugin-react-hooks@5.0.0'
          - 'eslint-plugin-awscdk@4.3.2'
          - 'eslint-visitor-keys@3.1.0'
