version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      PORT: 4000
      PROFILE_IMAGE_BUCKET_NAME: ${PROFILE_IMAGE_BUCKET_NAME}
      AWS_PROFILE: ${AWS_PROFILE}
    volumes:
      - ~/.aws:/root/.aws
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:4000/graphql/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_GATEWAY_ENDPOINT: http://localhost:4000/
      CHOKIDAR_USEPOLLING: true
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
