import { Resolvers } from '../schema/generated/resolvers.generated';
import {
  userQuery,
  userProfilePicturePresignedUrlQuery,
  userResolvers,
  updateUserProfilePicture,
  createUser,
  updateUserSettings,
  updateTravelPreferences,
  deleteUser,
} from './user';
import {
  journeysQuery,
  monitorJourney,
  updateJourneyMonitors,
  updateJourneyMonitor,
  deleteJourneyMonitor,
} from './journey';
import { locationsQuery } from './location';
import { markNotificationAsRead, sendEmailNotification, notificationResolvers } from './notification';
import { DateTimeResolver } from 'graphql-scalars';
import { GraphQLScalarType } from 'graphql';

// Extend Resolvers with scalar resolvers not generated by codegen.
type ResolversWithScalars = Resolvers & { DateTime: GraphQLScalarType };

const resolvers: ResolversWithScalars = {
  DateTime: DateTimeResolver,
  User: userResolvers,
  Notification: notificationResolvers,
  Query: {
    user: userQuery,
    userProfilePicturePresignedUrl: userProfilePicturePresignedUrlQuery,
    journeys: journeysQuery,
    locations: locationsQuery,
  },
  Mutation: {
    updateUserProfilePicture: updateUserProfilePicture,
    createUser: createUser,
    updateUserSettings: updateUserSettings,
    updateTravelPreferences: updateTravelPreferences,
    deleteUser: deleteUser,
    monitorJourney: monitorJourney,
    updateJourneyMonitors: updateJourneyMonitors,
    updateJourneyMonitor: updateJourneyMonitor,
    deleteJourneyMonitor: deleteJourneyMonitor,
    markNotificationAsRead: markNotificationAsRead,
    sendEmailNotification: sendEmailNotification,
  },
};

export default resolvers;
